const themes=[
{name:"Antique Gold",accent:"#8C7143",soft:"#D6C7A8"},
{name:"Forest",accent:"#4D715B",soft:"#BDD0C2"},
{name:"Terracotta",accent:"#9C5D45",soft:"#D8B8AA"},
{name:"Mountain Blue",accent:"#526D7A",soft:"#BCCBD2"},
{name:"Plum",accent:"#72586D",soft:"#C7BBC4"},
{name:"Cedar",accent:"#755B3E",soft:"#CBBDA9"},
{name:"Sage",accent:"#68785A",soft:"#C4CCBA"},
{name:"Burgundy",accent:"#7E3547",soft:"#D0B2B9"}];
const fonts=["Cormorant Garamond","Playfair Display","Bodoni Moda","DM Serif Display","Prata","Manrope"];
const root=document.documentElement,reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,systemDark=matchMedia("(prefers-color-scheme: dark)");
let themeIndex=0,fontIndex=0,colourLocked=false,fontLocked=false,selectedMode="light",selectedRoom="Any Available Stay";
const swatches=document.getElementById("themeSwatches"),customColour=document.getElementById("customColour"),customHex=document.getElementById("customHex"),fontSelect=document.getElementById("fontSelect"),colourStatus=document.getElementById("colourStatus"),fontStatus=document.getElementById("fontStatus"),modeStatus=document.getElementById("modeStatus"),lockColour=document.getElementById("lockColour"),lockFont=document.getElementById("lockFont"),lockBoth=document.getElementById("lockBoth");
function hexToRgb(hex){const c=String(hex).replace("#","");if(!/^[0-9a-fA-F]{6}$/.test(c))return null;return[parseInt(c.slice(0,2),16),parseInt(c.slice(2,4),16),parseInt(c.slice(4,6),16)]}
function mix(hex,a=.64){const r=hexToRgb(hex);return r?`#${r.map(v=>Math.round(v+(255-v)*a).toString(16).padStart(2,"0")).join("")}`:"#D6C7A8"}
function applyTheme(t,i=-1){const rgb=hexToRgb(t.accent);if(!rgb)return;root.style.setProperty("--accent",t.accent);root.style.setProperty("--accent-rgb",rgb.join(","));root.style.setProperty("--accent-soft",t.soft||mix(t.accent));customColour.value=t.accent;customHex.value=t.accent.toUpperCase();document.querySelector('meta[name="theme-color"]').content=t.accent;[...swatches.children].forEach((b,n)=>b.classList.toggle("active",n===i))}
function applyFont(f){root.style.setProperty("--display",`"${f}",Georgia,serif`);fontSelect.value=f}
function resolveMode(m){root.dataset.mode=m==="system"?(systemDark.matches?"dark":"light"):m;modeStatus.textContent=m[0].toUpperCase()+m.slice(1);document.querySelectorAll("[data-mode-value]").forEach(b=>b.classList.toggle("active",b.dataset.modeValue===m))}
function updateLocks(){lockColour.classList.toggle("locked",colourLocked);lockFont.classList.toggle("locked",fontLocked);lockBoth.classList.toggle("locked",colourLocked&&fontLocked);lockColour.querySelector("b").textContent=colourLocked?"Locked":"Unlocked";lockFont.querySelector("b").textContent=fontLocked?"Locked":"Unlocked";colourStatus.textContent=colourLocked?"Locked":reduced?"Manual":"Auto · 3 sec";fontStatus.textContent=fontLocked?"Locked":reduced?"Manual":"Auto · 3 sec";lockBoth.textContent=colourLocked&&fontLocked?"Unlock Both":"Lock Both"}
themes.forEach((t,i)=>{const b=document.createElement("button");b.type="button";b.style.setProperty("--swatch",t.accent);b.title=t.name;b.onclick=()=>{themeIndex=i;applyTheme(t,i)};swatches.appendChild(b)});
applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks();
if(!reduced){setInterval(()=>{if(!colourLocked){themeIndex=(themeIndex+1)%themes.length;applyTheme(themes[themeIndex],themeIndex)}},3000);setInterval(()=>{if(!fontLocked){fontIndex=(fontIndex+1)%fonts.length;applyFont(fonts[fontIndex])}},3000)}
customColour.oninput=e=>applyTheme({accent:e.target.value.toUpperCase(),soft:mix(e.target.value)});customHex.onchange=e=>{let v=e.target.value.trim();if(!v.startsWith("#"))v="#"+v;hexToRgb(v)?applyTheme({accent:v.toUpperCase(),soft:mix(v)}):e.target.value=getComputedStyle(root).getPropertyValue("--accent").trim()};fontSelect.onchange=e=>{fontIndex=Math.max(0,fonts.indexOf(e.target.value));applyFont(e.target.value)};lockColour.onclick=()=>{colourLocked=!colourLocked;updateLocks()};lockFont.onclick=()=>{fontLocked=!fontLocked;updateLocks()};lockBoth.onclick=()=>{const v=!(colourLocked&&fontLocked);colourLocked=v;fontLocked=v;updateLocks()};document.querySelectorAll("[data-mode-value]").forEach(b=>b.onclick=()=>{selectedMode=b.dataset.modeValue;resolveMode(selectedMode)});systemDark.onchange=()=>selectedMode==="system"&&resolveMode("system");document.getElementById("resetCustomizer").onclick=()=>{themeIndex=fontIndex=0;colourLocked=fontLocked=false;selectedMode="light";applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks()};
const customizer=document.querySelector(".customizer"),customizerToggle=document.getElementById("customizerToggle");function setCustomizer(o){customizer.classList.toggle("open",o);customizerToggle.setAttribute("aria-expanded",o)}customizerToggle.onclick=()=>setCustomizer(!customizer.classList.contains("open"));document.getElementById("customizerClose").onclick=()=>setCustomizer(false);
const body=document.body,menuButton=document.getElementById("menuButton"),mainNav=document.getElementById("mainNav");menuButton.onclick=()=>{const o=mainNav.classList.toggle("open");body.classList.toggle("locked",o);menuButton.setAttribute("aria-expanded",o)};mainNav.querySelectorAll("a").forEach(a=>a.onclick=()=>{mainNav.classList.remove("open");body.classList.remove("locked")});
document.querySelectorAll(".reveal").forEach(el=>{if(reduced)el.classList.add("visible");else new IntersectionObserver((entries,obs)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.1}).observe(el)});

const today=new Date(),checkinDate=new Date(today);checkinDate.setDate(today.getDate()+1);const checkoutDate=new Date(today);checkoutDate.setDate(today.getDate()+3);const dateString=d=>d.toISOString().split("T")[0];
const checkIn=document.getElementById("checkIn"),checkOut=document.getElementById("checkOut");checkIn.min=dateString(checkinDate);checkIn.value=dateString(checkinDate);checkOut.min=dateString(checkoutDate);checkOut.value=dateString(checkoutDate);
checkIn.onchange=()=>{const d=new Date(checkIn.value);d.setDate(d.getDate()+1);checkOut.min=dateString(d);if(checkOut.value<checkOut.min)checkOut.value=checkOut.min};

const roomCards=[...document.querySelectorAll(".room-card")],roomButtons=[...document.querySelectorAll("[data-room-filter]")],occupancy=document.getElementById("occupancyFilter"),roomEmpty=document.getElementById("roomEmpty");let roomFilter="All";
function filterRooms(){let count=0;roomCards.forEach(c=>{const ok=(roomFilter==="All"||c.dataset.roomCategory===roomFilter)&&Number(c.dataset.occupancy)>=Number(occupancy.value);c.hidden=!ok;if(ok)count++});roomEmpty.hidden=count!==0}
roomButtons.forEach(b=>b.onclick=()=>{roomFilter=b.dataset.roomFilter;roomButtons.forEach(x=>x.classList.toggle("active",x===b));filterRooms()});occupancy.onchange=filterRooms;

const bookingModal=document.getElementById("bookingModal"),roomModal=document.getElementById("roomModal"),simpleModal=document.getElementById("simpleModal"),mapModal=document.getElementById("mapModal"),galleryModal=document.getElementById("galleryModal");
function openD(d){d.showModal();body.classList.add("locked")}function closeD(d){d.close();body.classList.remove("locked")}
const bookingForm=document.getElementById("bookingForm");bookingForm.elements.checkin.min=checkIn.min;bookingForm.elements.checkin.value=checkIn.value;bookingForm.elements.checkout.min=checkOut.min;bookingForm.elements.checkout.value=checkOut.value;
function openBooking(){bookingForm.elements.stay.value=selectedRoom;openD(bookingModal)}
document.querySelectorAll("[data-open-booking]").forEach(b=>b.onclick=openBooking);document.getElementById("bookingClose").onclick=()=>closeD(bookingModal);bookingModal.onclick=e=>e.target===bookingModal&&closeD(bookingModal);
document.getElementById("heroSearch").onsubmit=e=>{e.preventDefault();bookingForm.elements.checkin.value=checkIn.value;bookingForm.elements.checkout.value=checkOut.value;bookingForm.elements.guests.value=`${document.getElementById("guestCount").value}${document.getElementById("guestCount").value==="1"?" Guest":" Guests"}`;openBooking()};

document.querySelectorAll("[data-room]").forEach(b=>b.onclick=()=>{selectedRoom=b.dataset.room;document.getElementById("roomModalTitle").textContent=selectedRoom;document.getElementById("roomModalType").textContent=b.dataset.type;document.getElementById("roomModalRate").textContent=b.dataset.rate;roomModal.querySelector(".room-modal-media").style.backgroundImage=`url("${b.dataset.image}")`;openD(roomModal)});
document.getElementById("roomClose").onclick=()=>closeD(roomModal);roomModal.onclick=e=>e.target===roomModal&&closeD(roomModal);document.getElementById("roomBook").onclick=()=>{closeD(roomModal);openBooking()};

function openSimple(eyebrow,title,text,message){document.getElementById("simpleEyebrow").textContent=eyebrow;document.getElementById("simpleTitle").textContent=title;document.getElementById("simpleText").textContent=text;document.getElementById("simpleLink").href=`https://wa.me/919929562585?text=${encodeURIComponent(message)}`;openD(simpleModal)}
document.querySelectorAll("[data-offer]").forEach(b=>b.onclick=()=>openSimple("OFFER ENQUIRY · DEMO",b.dataset.offer,"No real rate or package is offered. Discuss an offers section for a hotel website.",`Hello Ajay, I am viewing the Aurevia demo. I want a hotel offers feature like: ${b.dataset.offer}.`));
document.querySelectorAll("[data-experience]").forEach(b=>b.onclick=()=>openSimple("EXPERIENCE ENQUIRY · DEMO",b.dataset.experience,"This fictional activity demonstrates a bookable experience journey.",`Hello Ajay, I am viewing the Aurevia demo. I want an experience-booking feature for: ${b.dataset.experience}.`));
document.querySelectorAll("[data-open-spa]").forEach(b=>b.onclick=()=>openSimple("SPA RESERVATION · DEMO","Reserve a quieter hour.","This portfolio feature prepares a spa enquiry on WhatsApp.","Hello Ajay, I am viewing the Aurevia demo. I want a hotel spa-booking feature."));
document.querySelectorAll("[data-open-dining]").forEach(b=>b.onclick=()=>openSimple("DINING RESERVATION · DEMO","Reserve a table.","A real version can connect date, time, covers and venue inventory.","Hello Ajay, I am viewing the Aurevia demo. I want a restaurant reservation feature inside a hotel website."));
document.querySelectorAll("[data-open-event]").forEach(b=>b.onclick=()=>openSimple("WEDDING ENQUIRY · DEMO","Plan a celebration above the valley.","A real event form can capture dates, functions, rooms, guests and venue preferences.","Hello Ajay, I am viewing the Aurevia demo. I want a hotel wedding and events enquiry flow."));
document.querySelectorAll("[data-open-contact]").forEach(b=>b.onclick=()=>openSimple("CONTACT AUREVIA · DEMO","Talk to the hotel team.","This demonstration routes enquiries to AJAYNXT.","Hello Ajay, I am viewing the Aurevia Retreat demo and want details about a hotel website."));
document.getElementById("simpleClose").onclick=()=>closeD(simpleModal);simpleModal.onclick=e=>e.target===simpleModal&&closeD(simpleModal);
document.querySelectorAll("[data-open-map]").forEach(b=>b.onclick=()=>openD(mapModal));document.getElementById("mapClose").onclick=()=>closeD(mapModal);mapModal.onclick=e=>e.target===mapModal&&closeD(mapModal);

const dining={
"Cedar Table":{image:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1700&q=88",type:"ALL-DAY DINING",description:"Seasonal Indian and international menus overlooking the forest canopy.",hours:"Demo hours · 7:00 AM to 11:00 PM"},
"The Glasshouse":{image:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1700&q=88",type:"SIGNATURE RESTAURANT",description:"A slower tasting-menu concept inspired by mountain produce and fire.",hours:"Demo hours · 7:00 PM to 11:00 PM"},
"Ember Lounge":{image:"https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1700&q=88",type:"LOUNGE & BAR",description:"Cocktails, small plates and fireside conversations after sunset.",hours:"Demo hours · 4:00 PM to midnight"}
};
document.querySelectorAll("[data-dining]").forEach(b=>b.onclick=()=>{const d=dining[b.dataset.dining];document.querySelectorAll("[data-dining]").forEach(x=>x.classList.toggle("active",x===b));document.getElementById("diningImage").src=d.image;document.getElementById("diningTitle").textContent=b.dataset.dining;document.getElementById("diningType").textContent=d.type;document.getElementById("diningDescription").textContent=d.description;document.getElementById("diningHours").textContent=d.hours});

const galleryPreview=document.getElementById("galleryPreview");document.querySelectorAll("[data-gallery]").forEach(b=>b.onclick=()=>{galleryPreview.src=b.dataset.gallery;openD(galleryModal)});document.getElementById("galleryClose").onclick=()=>closeD(galleryModal);galleryModal.onclick=e=>e.target===galleryModal&&closeD(galleryModal);
document.querySelectorAll(".faq-list button").forEach(b=>b.onclick=()=>{const o=b.getAttribute("aria-expanded")==="true";document.querySelectorAll(".faq-list button").forEach(x=>x.setAttribute("aria-expanded","false"));b.setAttribute("aria-expanded",String(!o))});

function setErr(input,msg){input.setAttribute("aria-invalid",String(Boolean(msg)));const s=input.closest("label")?.querySelector(".field-error");if(s)s.textContent=msg;return!msg}
function validate(i){if(i.required&&!i.value.trim())return setErr(i,"This field is required.");if(i.name==="phone"&&!/^[0-9+\s()-]{8,18}$/.test(i.value.trim()))return setErr(i,"Enter a valid phone number.");return setErr(i,"")}
function validForm(f){const fields=[...f.querySelectorAll("[required]")],ok=fields.map(validate).every(Boolean);if(!ok)fields.find(x=>x.getAttribute("aria-invalid")==="true")?.focus();return ok}
bookingForm.onsubmit=e=>{e.preventDefault();if(!validForm(bookingForm))return;const d=new FormData(bookingForm),msg=["Hello Ajay, I am viewing the Aurevia Retreat demo.","","Demo stay enquiry:",`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Check-in: ${d.get("checkin")}`,`Check-out: ${d.get("checkout")}`,`Guests: ${d.get("guests")}`,`Preferred Stay: ${d.get("stay")}`,`Notes: ${d.get("notes")||""}`,"","I also want information about a hotel website."].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
const priceForm=document.getElementById("priceForm");priceForm.onsubmit=e=>{e.preventDefault();if(!validForm(priceForm))return;const d=new FormData(priceForm),msg=["Hello Ajay, I want a hotel or resort website price.","",`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Hotel / Resort: ${d.get("business")||""}`,`Website Type: ${d.get("type")}`,`Project Details: ${d.get("message")||""}`,"","Reference: Aurevia Retreat Demo"].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
